spring:
  application:
    name: authorization
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false
    username: oauth2
    password: oauth2
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:/script/schema.sql
    data: classpath:/script/data.sql

server:
  port: 8001